trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'

  - script: |
      python -m pip install --upgrade pip
      pip install pytest homeassistant pytest-homeassistant-custom-component aiohttp flake8 mypy
    displayName: 'Install dependencies'

  - script: |
      flake8 .
    displayName: 'Lint with flake8'
    continueOnError: 'true'

  - script: |
      mypy custom_components/alplakes
    displayName: 'Type-check with mypy'

  - script: |
      pytest --maxfail=1 --disable-warnings -q
    displayName: 'Run unit tests'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/junit-*.xml'
