name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Allows manual triggering (for e2e or deploy runs)

jobs:
  # 1. Build: install deps, lint, type‑check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Type-check with mypy
        run: mypy custom_components/ha-alplakes

  # 2. Test (unit)
  unit-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
        
      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q -m "not integration"

  # 3. Integration‑Test (real API)
  integration-test:
    needs: unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt -r requirements-dev.txt
        
      - name: Run integration tests
        run: pytest -q -m integration

  # 4. Deploy to Testbed (AKS Home Assistant)
  deploy:
    needs: integration-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Copy to Home Assistant testbed via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HA_HOST }}
          username: ${{ secrets.HA_USER }}
          key: ${{ secrets.HA_SSH_KEY }}
          source: "custom_components/ha-alplakes/"
          target: "/config/custom_components/ha-alplakes/"

      - name: Restart Home Assistant
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HA_HOST }}
          username: ${{ secrets.HA_USER }}
          key: ${{ secrets.HA_SSH_KEY }}
          script: |
            ha core restart

  # 5. End‑to‑End Test (verify sensor in running HA)
  e2e-test:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Wait for Home Assistant to come up
        run: sleep 30

      - name: Check sensor via Home Assistant REST API
        run: |
          curl -s -X GET "http://${{ secrets.HA_HOST }}:8123/api/states/{{ secrets.HA_ENTITY_ID }}" \
            -H "Authorization: Bearer ${{ secrets.HA_TOKEN }}" | jq .

      - name: Assert valid temperature
        run: |
          TEMP=$(curl -s -X GET "http://${{ secrets.HA_HOST }}:8123/api/states/${{ secrets.HA_ENTITY_ID }}" \
            -H "Authorization: Bearer ${{ secrets.HA_TOKEN }}" | jq -r '.state')
          awk "BEGIN { exit !($TEMP+0 >= 0 && $TEMP+0 <= 40) }"  # exits 0 if 0≤TEMP≤40
