name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:   # Allows manual triggering (for e2e or deploy runs)

jobs:
  # Build: install deps, lint, type-check
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-dev.txt

      - name: Lint with flake8
        continue-on-error: true
        run: flake8 .

      - name: Type-check with mypy
        run: mypy custom_components/alplakes
